{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "codefresh-runner.serviceAccountName" . }}

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: codefresh-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: codefresh-role
subjects:
- kind: ServiceAccount
  name: {{ include "codefresh-runner.serviceAccountName" . }}
  namespace: $NAMESPACE

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: codefresh-role
rules:
  - apiGroups: [""]
    resources: ["pods", "persistentvolumeclaims", "persistentvolumes"]
    verbs: ["list", "watch", "get", "create", "patch", "delete"] 
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshots"]
    verbs: ["list", "watch", "get", "create", "patch", "delete"] 

{{- end -}}