apiVersion: v1
kind: ConfigMap
metadata:
  name: upgrade-script
  namespace: {{ include "codefresh-runner.namespace" . }}
data:
  upgrade.sh: |
   #!/bin/bash
   echo "Start Upgrade"

   echo codefresh auth create-context $CF_ARG_KUBE_CONTEXT_NAME --api-key $CODEFRESH_TOKEN --kube-namespace $CF_ARG_KUBE_NAMESPACE
   codefresh auth create-context $CF_ARG_KUBE_CONTEXT_NAME --api-key $CODEFRESH_TOKEN --kube-namespace $CF_ARG_KUBE_NAMESPACE
   echo codefresh runner upgrade  --agent-name $CF_AGENT_NAME --kube-context-name $CF_ARG_KUBE_CONTEXT_NAME
   codefresh runner upgrade  --agent-name $CF_AGENT_NAME --kube-context-name $CF_ARG_KUBE_CONTEXT_NAME

   echo "Finish"